### ISSUE TITLE
E2E tests (s3s-e2e)

### ISSUE THREAD

**Issue by Nugine** [s3s-project/s3s#187]
## s3s-test
+ [x] accept cli options
+ [x] list all tests
+ [x] regex filter
+ [ ] ignored tests
+ [ ] run tests concurrently

## s3s-e2e
+ [x] include build info in binary

## Rewrite from [minio/mint](https://github.com/minio/mint)

[crates/s3s-e2e/src/main.rs](https://github.com/Nugine/s3s/blob/main/crates/s3s-e2e/src/main.rs)
[crates/s3s-e2e/src/basic.rs](https://github.com/Nugine/s3s/blob/main/crates/s3s-e2e/src/basic.rs)
[crates/s3s-e2e/src/advanced.rs](https://github.com/Nugine/s3s/blob/main/crates/s3s-e2e/src/advanced.rs)

+ [ ] mc: https://github.com/minio/mc/blob/master/functional-tests.sh

**Comment by Nugine** [comment]
Replaced by #266
