### ISSUE TITLE
Fuzz

### ISSUE THREAD

**Issue by Nugine** [s3s-project/s3s#86]
+ [x] fuzz infra (weekly)
+ [x] fuzz tests (basic)
+ [x] verify the Continuous Fuzz infrastructure

**Comment by Nugine** [comment]
+ https://github.com/rustfs/rustfs/issues/3519
+ https://github.com/rustfs/rustfs/issues/3532

**Comment by Nugine** [comment]
+ #724 
+ #726 
+ #727 
+ #728 
+ #730 
+ #731 
+ #733 
+ #735
